package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF005AC1)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD8E2FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001A41)
val md_theme_light_secondary = Color(0xFF535E78)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_background = Color(0xFFFDFBFF)
val md_theme_light_onBackground = Color(0xFF1A1C1E)
val md_theme_light_surface = Color(0xFFFDFBFF)
val md_theme_light_onSurface = Color(0xFF1A1C1E)
val md_theme_light_surfaceVariant = Color(0xFFF1F4F9)
val md_theme_light_onSurfaceVariant = Color(0xFF43474E)
val md_theme_light_outline = Color(0xFFDDE2EA)
val md_theme_light_outlineVariant = Color(0xFFC4C6D0)

val md_theme_dark_primary = Color(0xFFADC6FF)
val md_theme_dark_onPrimary = Color(0xFF002E69)
val md_theme_dark_primaryContainer = Color(0xFF004493)
val md_theme_dark_onPrimaryContainer = Color(0xFFD8E2FF)
val md_theme_dark_secondary = Color(0xFFBBC6E4)
val md_theme_dark_onSecondary = Color(0xFF253048)
val md_theme_dark_background = Color(0xFF1A1C1E)
val md_theme_dark_onBackground = Color(0xFFE2E2E6)
val md_theme_dark_surface = Color(0xFF1A1C1E)
val md_theme_dark_onSurface = Color(0xFFE2E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF43474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C6D0)
val md_theme_dark_outline = Color(0xFF8E9099)
val md_theme_dark_outlineVariant = Color(0xFF43474E)

val LogSuccess = Color(0xFFA5D6A7)
val LogInfo = Color(0xFFBBDEFB)
val LogWarn = Color(0xFFFFE082)
val LogDefault = Color(0xFFE2E2E6)
val LogBackground = Color(0xFF1A1C1E)